"""Builds every source in src/ into one LTCG image, build/halo2.exe, with its
map build/halo2.map, so tools/check.py can compare its functions with retail.

Each source is compiled with its own flags (a "// @flags" line in the source,
else config/files.json). Each function
marked "// @retail 0x..." gets a stand-in caller, compiled for size without
inlining. The stand-in keeps the function in the image and out of line, as
retail's own callers do. Sources in src/stubs/ are compiled without /GL, so
they keep the standard calling conventions retail uses for code outside the
project.

    python tools/build.py
"""
import json
import os
import re
import subprocess
from dataclasses import dataclass

from xbe import ROOT, xdk_dir

MARKER = re.compile(r'^\s*//\s*@retail\s+(0x[0-9a-fA-F]+)\s*$')
FLAGS = re.compile(r'^\s*//\s*@flags\s+(.+?)\s*$')
FLAGS_LINES = 30
INCLUDE = re.compile(r'^\s*#\s*include\s+"[^"]+"')
SIZE_FLAGS = ['/O1', '/Ob0', '/Gr']
ARGUMENT_STRIDE = 16
LIBRARIES = ['libcmt.lib', 'libcpmt.lib', 'xapilib.lib', 'xboxkrnl.lib', 'dsound.lib', 'xonlines.lib',
             'xvoice.lib', 'xnet.lib', 'd3d8ltcg.lib', 'xgraphicsltcg.lib', 'd3dx8.lib']
EXE_NAME = 'halo2.exe'
MAP_NAME = 'halo2.map'


@dataclass
class Marked:
    path: str
    retail: int
    name: str
    returns: str
    params: list


def _split_params(text):
    parts, depth, current = [], 0, ''
    for ch in text:
        if ch in '(<[':
            depth += 1
        elif ch in ')>]':
            depth -= 1
        if ch == ',' and depth == 0:
            parts.append(current)
            current = ''
        else:
            current += ch
    if current.strip():
        parts.append(current)
    return [p.strip() for p in parts]


def _param_type(param):
    """'unsigned long *crc_reference' -> 'unsigned long *'."""
    param = param.split('=')[0].strip()
    m = re.match(r'^(.*?)([A-Za-z_]\w*)\s*(\[\s*\d*\s*\])?$', param)
    if m and m.group(1).strip() and not m.group(1).strip().endswith(('struct', 'union', 'enum')):
        kind = m.group(1).strip()
        return kind + ' *' if m.group(3) else kind
    return param


def scan(text, path):
    lines = text.splitlines()
    found = []
    for i, line in enumerate(lines):
        m = MARKER.match(line)
        if not m:
            continue
        header = ''
        for later in lines[i + 1:]:
            header += ' ' + later.split('//')[0]
            if '{' in later:
                break
        header = ' '.join(header.split('{')[0].split())
        h = re.match(r'^(?:PRIVATE\s+)?(?:inline\s+|__inline\s+)?(.*?)\s*([A-Za-z_][\w:]*)\s*\((.*)\)\s*$', header)
        if not h:
            raise SystemExit(f'{path}:{i + 2}: cannot read the function after @retail {m.group(1)}')
        params = [_param_type(p) for p in _split_params(h.group(3))]
        if params == ['void']:
            params = []
        found.append(Marked(path, int(m.group(1), 16), h.group(2), h.group(1).strip() or 'int', params))
    return found


def standin_source(source_path, includes, marked, prefix):
    out = [f'/* generated by tools/build.py from {source_path}: stand-in callers */']
    out += includes
    out.append(f'static unsigned char volatile standin_{prefix}_arguments[{ARGUMENT_STRIDE * 16}];')
    for m in marked:
        if '::' in m.name:
            raise SystemExit(f'{source_path}: {m.name} is a member function: member functions need a '
                             'caller in src/; generated stand-ins cannot call them yet')
        out.append(f'{m.returns} {m.name}({", ".join(m.params)});')
    for k, m in enumerate(marked):
        args = ', '.join(
            f'*({p} volatile *)(standin_{prefix}_arguments + {ARGUMENT_STRIDE * n})'
            for n, p in enumerate(m.params))
        call = f'{m.name}({args})'
        if m.returns != 'void':
            out.append(f'static {m.returns} volatile standin_{prefix}_result_{k};')
            call = f'standin_{prefix}_result_{k} = {call}'
        out.append(f'void standin_{prefix}_{k}(void) {{ {call}; }}')
    return '\n'.join(out) + '\n'


def run_tool(tool, args, cwd, xdk):
    env = dict(os.environ, INCLUDE=os.path.join(xdk, 'include'), LIB=os.path.join(xdk, 'lib'))
    p = subprocess.run([os.path.join(xdk, 'bin', 'vc71', tool), '/nologo', *args], cwd=cwd, env=env,
                       capture_output=True, text=True)
    if p.returncode:
        raise SystemExit(f'{tool} failed:\n{p.stdout}{p.stderr}')


def _stale(target, sources, newest_header):
    if not os.path.exists(target):
        return True
    t = os.path.getmtime(target)
    return newest_header > t or any(os.path.getmtime(s) > t for s in sources)


def source_flags(flags):
    """What every source in src/ is compiled with, whatever files.json says:
    LTCG, and the register calling convention retail's code uses."""
    return ['/GL', '/Gr', *flags]


def file_flags(text, name, config):
    """A source's own flags: its "// @flags ..." line among the first 30 lines,
    else its entry in config/files.json, else the default."""
    for line in text.splitlines()[:FLAGS_LINES]:
        m = FLAGS.match(line)
        if m:
            return m.group(1).split()
    return config.get('files', {}).get(name, config['default'])


def _source_names(root):
    src = os.path.join(root, 'src')
    return sorted(n for n in os.listdir(src) if n.endswith('.cpp')) if os.path.isdir(src) else []


def marked_sources(root=ROOT):
    """Every function marked "// @retail 0x..." in src/*.cpp, in file order."""
    marked = []
    for name in _source_names(root):
        with open(os.path.join(root, 'src', name), encoding='utf-8') as f:
            marked += scan(f.read(), f'src/{name}')
    return marked


def build(root=ROOT, xdk=None):
    xdk = xdk or xdk_dir()
    if not os.path.exists(os.path.join(xdk, 'bin', 'vc71', 'CL.Exe')):
        raise SystemExit(f'Xbox SDK 5849 not found at {xdk}. Put its xbox folder at sdk/xbox, '
                         'or set XDK_DIR to it.')
    src, out = os.path.join(root, 'src'), os.path.join(root, 'build')
    obj_dir, gen = os.path.join(out, 'obj'), os.path.join(out, 'gen')
    os.makedirs(obj_dir, exist_ok=True)
    os.makedirs(gen, exist_ok=True)
    with open(os.path.join(root, 'config', 'files.json'), encoding='utf-8') as f:
        config = json.load(f)
    headers = [os.path.join(d, n) for base in ('include', 'src') for d, _, ns in os.walk(os.path.join(root, base))
               for n in ns if n.endswith('.h')]
    newest_header = max((os.path.getmtime(h) for h in headers), default=0)
    includes = ['/I', os.path.join(root, 'include'), '/I', src]
    marked_by_path = {}
    for m in marked_sources(root):
        marked_by_path.setdefault(m.path, []).append(m)

    objects, entry_calls, entry_decls = [], [], []
    for name in _source_names(root):
        path = os.path.join(src, name)
        stem = os.path.splitext(name)[0]
        with open(path, encoding='utf-8') as f:
            text = f.read()
        flags = file_flags(text, name, config)
        obj = os.path.join(obj_dir, stem + '.obj')
        if _stale(obj, [path, os.path.join(root, 'config', 'files.json')], newest_header):
            run_tool('CL.Exe', ['/c', *source_flags(flags), *includes, path, f'/Fo{obj}'], root, xdk)
        objects.append(obj)
        marked = marked_by_path.get(f'src/{name}')
        if marked:
            gen_path = os.path.join(gen, f'standins_{stem}.cpp')
            source = standin_source(f'src/{name}', [l for l in text.splitlines() if INCLUDE.match(l)],
                                    marked, stem)
            if not os.path.exists(gen_path) or open(gen_path, encoding='utf-8').read() != source:
                with open(gen_path, 'w', encoding='utf-8') as f:
                    f.write(source)
            gen_obj = os.path.join(obj_dir, f'standins_{stem}.obj')
            if _stale(gen_obj, [gen_path], newest_header):
                run_tool('CL.Exe', ['/c', '/GL', *SIZE_FLAGS, *includes, gen_path, f'/Fo{gen_obj}'], root, xdk)
            objects.append(gen_obj)
            for k in range(len(marked)):
                entry_decls.append(f'void standin_{stem}_{k}(void);')
                entry_calls.append(f'\tstandin_{stem}_{k}();')

    folder = os.path.join(src, 'stubs')
    if os.path.isdir(folder):
        for name in sorted(n for n in os.listdir(folder) if n.endswith('.cpp')):
            path = os.path.join(folder, name)
            obj = os.path.join(obj_dir, f'stubs_{os.path.splitext(name)[0]}.obj')
            if _stale(obj, [path], newest_header):
                run_tool('CL.Exe', ['/c', '/O2', '/Gr', *includes, path, f'/Fo{obj}'], root, xdk)
            objects.append(obj)

    entry = os.path.join(gen, 'entry.cpp')
    entry_text = ('/* generated by tools/build.py: the image entry point */\n'
                  'extern "C" int _fltused = 0;\n' + '\n'.join(entry_decls) +
                  '\nextern "C" int entry(void)\n{\n' + '\n'.join(entry_calls) + '\n\treturn 0;\n}\n')
    entry_obj = os.path.join(obj_dir, 'entry.obj')
    if not os.path.exists(entry) or open(entry, encoding='utf-8').read() != entry_text:
        with open(entry, 'w', encoding='utf-8') as f:
            f.write(entry_text)
    if _stale(entry_obj, [entry], newest_header):
        run_tool('CL.Exe', ['/c', '/GL', *SIZE_FLAGS, entry, f'/Fo{entry_obj}'], root, xdk)
    objects.append(entry_obj)

    exe, map_path = os.path.join(out, EXE_NAME), os.path.join(out, MAP_NAME)
    run_tool('Link.Exe', ['/LTCG', '/NODEFAULTLIB', '/ENTRY:entry', '/SUBSYSTEM:CONSOLE', '/MAP:' + map_path,
                          '/MAPINFO:FIXUPS', '/FIXED:NO', f'/OUT:{exe}', *objects, *LIBRARIES], root, xdk)
    return map_path


if __name__ == '__main__':
    print(build())
